-- Proposed beer releases — staging table for Content Admin review.
-- Mirrors public.beer_releases_base. Apply in Supabase SQL Editor.
-- Safe to re-run (IF NOT EXISTS / DROP POLICY IF EXISTS).
--
-- Note: Hoppenings Content Admin mutations use the service_role key, which
-- bypasses RLS. Policies below still allow authenticated users with
-- profiles.admin = true to read/write via the anon/authenticated clients.

-- =============================================================================
-- 1) Table
-- =============================================================================

create table if not exists public.proposed_beer_releases (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  beer_name text null,
  description text null,
  brewery_id uuid null,
  "ABV" text null,
  "Type" text null,
  release_date date null,
  brewery_id2 uuid null,
  brewery_id3 uuid null,
  constraint proposed_beer_releases_pkey primary key (id),
  constraint proposed_beer_releases_brewery_id_fkey
    foreign key (brewery_id) references public.breweries (id) on delete set null,
  constraint proposed_beer_releases_brewery_id2_fkey
    foreign key (brewery_id2) references public.breweries (id) on delete set null,
  constraint proposed_beer_releases_brewery_id3_fkey
    foreign key (brewery_id3) references public.breweries (id) on delete set null
) tablespace pg_default;

create index if not exists proposed_beer_releases_brewery_id_idx
  on public.proposed_beer_releases using btree (brewery_id) tablespace pg_default;

create index if not exists proposed_beer_releases_release_date_idx
  on public.proposed_beer_releases using btree (release_date) tablespace pg_default
  where (release_date is not null);

create index if not exists proposed_beer_releases_created_at_idx
  on public.proposed_beer_releases using btree (created_at desc) tablespace pg_default;

comment on table public.proposed_beer_releases is
  'Staging beer releases awaiting Content Admin accept/reject (parallel to proposed_events).';

-- =============================================================================
-- 2) Grants
-- =============================================================================

grant select, insert, update, delete on table public.proposed_beer_releases to authenticated;
grant all on table public.proposed_beer_releases to service_role;

-- Identity PK sequence (needed for inserts from authenticated role)
grant usage, select on sequence public.proposed_beer_releases_id_seq to authenticated;
grant usage, select on sequence public.proposed_beer_releases_id_seq to service_role;

-- =============================================================================
-- 3) RLS — admins only (profiles.admin = true)
-- =============================================================================

alter table public.proposed_beer_releases enable row level security;

drop policy if exists "Admins can select proposed beer releases"
  on public.proposed_beer_releases;
drop policy if exists "Admins can insert proposed beer releases"
  on public.proposed_beer_releases;
drop policy if exists "Admins can update proposed beer releases"
  on public.proposed_beer_releases;
drop policy if exists "Admins can delete proposed beer releases"
  on public.proposed_beer_releases;

create policy "Admins can select proposed beer releases"
  on public.proposed_beer_releases
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.admin is true
    )
  );

create policy "Admins can insert proposed beer releases"
  on public.proposed_beer_releases
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.admin is true
    )
  );

create policy "Admins can update proposed beer releases"
  on public.proposed_beer_releases
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.admin is true
    )
  )
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.admin is true
    )
  );

create policy "Admins can delete proposed beer releases"
  on public.proposed_beer_releases
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.admin is true
    )
  );
